[4.x] add validation replacements to replicator and grid field types
statamic/cms pull request #10064
Opened 2024-05-14 08:17 UTC by florianbrinkmann

Currently it’s not possible to use the validation replacements (for example, `validation_rule_handle:{id}`) in fields that are part of replicator or grid fields, because the validator instance that is used for the »top-level« fields isn’t the same that’s used for the fields inside the replicator/grid (at least I think that’s the reason).

This PR changes that and adds the replacements for replicator and grid fields, if the parent is an Entry.

2024-05-24 10:38 UTC, duncanmcclean commented
We're [no longer accepting](https://statamic.dev/release-schedule-support-policy#support-policy) fixes to `4.x`, can you re-target this PR for `5.x`?

2024-05-24 14:00 UTC, jasonvarga requested changes
☝️ What Duncan said.

2024-05-28 17:51 UTC, jasonvarga commented
If this is still important for you, please feel free to update this PR to target 5.x and we can reopen. Or, open a fresh PR. Up to you. Thanks!

2024-05-28 17:51 UTC, closed without merging

2024-05-28 19:04 UTC, florianbrinkmann commented
Will update it next week

2024-06-03 15:15 UTC, florianbrinkmann commented
I created a new PR, because it seems I cannot re-target the existing one https://github.com/statamic/cms/pull/10255