[5.x] Minor dark mode adjustments
statamic/cms pull request #10544
Opened 2024-08-01 11:51 UTC by heidkaemper

This pull request brings a few minor adjustments for dark mode:

- The "little-dot" for indicating the publishing status gets a darker shade of grey. (will be the same color as "draft" in the status column of entry listings)
- SVG icons in cp widget headers get the same same color as icons in the welcome widget.

Before:
![before](https://github.com/user-attachments/assets/f7839725-888f-4e63-b812-18ec8415e9ee)

After:
![after](https://github.com/user-attachments/assets/cfa0c452-3175-4f91-b58b-69048dc55832)

2024-08-01 14:32 UTC, jasonvarga requested changes
Thank you.

The status icons are good, but I think the widget icons need to go back the way they were. They were made darker on purpose.

I think the getting started widget icons should be made darker to match instead.

2024-08-01 14:53 UTC, heidkaemper commented
Sure, no problem, changes are made.
For my taste, the icons are a little too dark now. Maybe my monitor isn't calibrated properly. :-)

2024-08-01 14:56 UTC, jasonvarga commented
Thanks!

2024-08-01 15:30 UTC, merged

2024-08-02 10:12 UTC, dannyuk1982 commented
The icons look too dark for me too (Calibrated LG Ultrafine), I can hardly see the darker ones in dark mode.

2024-08-02 12:37 UTC, jackmcdade commented
> The icons look too dark for me too (Calibrated LG Ultrafine), I can hardly see the darker ones in dark mode.

Weird, they look good to me on the same exact monitor. I’ll have another look see.

2024-08-02 14:32 UTC, dannyuk1982 commented
You're vision is likely better than mine, I've got light eyes so pretty light sensitive and also astigmatism, so my eyes aren't too good at seeing subtle contrast differences on dark backgrounds, especially on backlit screens

2024-08-02 14:41 UTC, jackmcdade commented
Well let's make it work for everyone : D