[5.x] Add option to add filters from collection/taxonomy list to breadcrumb »back« link in single view
statamic/cms pull request #11243
Opened 2024-12-10 13:54 UTC by florianbrinkmann

I got the request from a client if it’s possible to change the link that points back to the collection list from the edit view, so that it includes search/filter/sort params that were set before the user entered the single view from the list. I found a corresponding feature request in statamic/ideas https://github.com/statamic/ideas/issues/1049, and this PR aims to add that functionality that can be enabled via a config key.

I’m not sure if that is the best place for the config key (and if the name is clear enough), and if it’s a good idea to extend the `Breadcrumbs` class, but I couldn’t fint another place where the method could go. Thought about adding a Trait, but left it this way for now.

2024-12-13 21:49 UTC, jasonvarga commented
Do you have a specific reason that you made it opt-in with a config? I don't really see a reason someone wouldn't want it.

2024-12-14 09:02 UTC, florianbrinkmann commented
No specific reason @jasonvarga, I just didn’t want to change a default behavior, that’s all :)

> I don't really see a reason someone wouldn't want it.

Yes, you’re right, me neither. Should I remove the opt-in?

2024-12-14 16:58 UTC, jasonvarga commented
I appreciate that 😄 Yeah, let's remove the opt-in.

2024-12-14 18:13 UTC, florianbrinkmann commented
Removed the opt-in and made a change to also add the `page` param

2024-12-16 17:24 UTC, jasonvarga requested changes
Could you please give me permission to push to your branch? Usually it would auto-close the PR if your branch doesn't give us permission. Weird. 🤔 

Or, please make the following change yourself:
- Remove additions to Breadcrumbs.php
- Change the `breadcrumbUrl` methods to the following.

```
    public function breadcrumbUrl()
    {
        $referer = request()->header('referer');
        $showUrl = $this->showUrl();

        return $referer && Str::before($referer, '?') === $showUrl ? $referer : $showUrl;
    }
```

This would just check that the refererer is the showUrl. If it is, use all the query parameters as-is.

This seems much simpler, but maybe you can see a reason for needing to do what you originally did.

2024-12-16 17:39 UTC, florianbrinkmann commented
That‘s really weird, the checkbox is active, and I had a PR first where it wasn’t allowed which was auto-closed (because I made it from an organization account).

![Bildschirmfoto 2024-12-16 um 18 36 38](https://github.com/user-attachments/assets/c87adbcf-bc9f-42a0-bfb7-362f478b6044)

Your changes look a lot better than my check-escalation indeed, I’ll give it a try tomorrow and apply the changes :)

2024-12-17 08:27 UTC, florianbrinkmann commented
@jasonvarga I made the changes

2024-12-17 15:46 UTC, merged

2024-12-27 09:01 UTC, lakkes-ra commented
Thanks for pushing this PR @jasonvarga 🔥