[trans] id_ID: 60% translation of validation.php
statamic/cms pull request #2426
Opened 2020-09-15 01:23 UTC by suabahasa

2020-09-15 15:52 UTC, jasonvarga commented
Thank you for this PR. Are you planning on adding the rest of the translations?

2020-09-15 19:24 UTC, ebeauchamps commented
Indonesian..interesting. Did you try following [those guidelines](https://statamic.dev/cp-translations#content) to help you out? language code should be "id"...but you already knows that!

2020-09-16 00:40 UTC, suabahasa commented
Yes, I will commit the rest translation progressively.

2020-09-16 00:42 UTC, jasonvarga commented
Great! Just mark the PR as ready for review when you're done.

2020-09-16 05:36 UTC, suabahasa commented
I have a little knowledge about using git, is it common that this pull request include commit from [182164f](https://github.com/statamic/cms/pull/2426/commits/182164fa30ff1f18b8405796ee409e7068709d77) and [b919007](https://github.com/statamic/cms/pull/2426/commits/b919007091a78bcb8695aa8f06e29d9bb08e9e66) ?

2020-09-16 06:18 UTC, ebeauchamps reviewed
Hello! you also have to generate an   id.json   file. You can also duplicate any other  xx.json  file found in vendor/statamic/cms/resources/lang, change the duplicate name to id.json and translate all English keys in Indonesian

2020-09-16 07:38 UTC, suabahasa commented
> 
> 
> Hello! you also have to generate an id.json file. You can also duplicate any other xx.json file found in vendor/statamic/cms/resources/lang, change the duplicate name to id.json and translate all English keys in Indonesian.

Hi. Thanks for guide.

2020-09-16 13:57 UTC, jasonvarga requested changes

2020-09-16 13:57 UTC, jasonvarga commented on resources/lang/id.json
> +    "Your working copy will be replaced by the contents of this revision.": ""
These are still empty.

2020-09-18 03:16 UTC, suabahasa commented on resources/lang/id.json
> +    "Your working copy will be replaced by the contents of this revision.": ""
Yes, will commit the rest soon

2020-09-25 10:17 UTC, damcclean commented
@suabahasa It looks like the values are no longer blank. Is this pull request ready for review?

2020-09-25 10:26 UTC, suabahasa commented
@damcclean there are left about 20% of string (id.json) not yet translated. A bit busy this week, will commit the 20% the rest and submit it for review

2020-09-25 10:27 UTC, damcclean commented
> @damcclean there are left about 20% of string (id.json) not yet translated. A bit busy this week, will commit the 20% the rest and submit it for review

No rush, just wanted to know how it's going 😄

2020-11-04 20:58 UTC, jasonvarga commented
If you don't mind, I'm going to use Google Translate to fill in the missing lines shortly just so I can get this merged. You can feel free to review it after I do that. Thank you for the progress!

2020-11-04 23:51 UTC, suabahasa commented
Sure, I will happy to review the translation. Thanks

2020-11-06 02:19 UTC, merged

2020-11-06 02:36 UTC, jasonvarga commented
Thank you again. I've filled in the translations in dfbc54c9