Laravel 8 support - bring guzzle adapter in house
statamic/cms pull request #2547
Opened 2020-09-27 01:22 UTC by edalzell

The Guzzle Adapter package doesn't support Guzzle 7 via constraints but does work with no changes. License was MIT, so brought in house so we can support Laravel 8.

All tests pass.

2020-09-27 01:26 UTC, edalzell commented
Alrighty all tests run locally anyway.

2020-09-27 10:56 UTC, damcclean commented
I think the reasons the tests are failing is due to the `laravel/legacy-factories` package requiring a minimum of PHP 7.3 but the tests are running for PHP 7.2 (as that's what Statamic supports). 

I would have thought moving it to be a dev dependency would have sorted but doesn't seem like it. 🤔

2020-09-27 16:19 UTC, jasonvarga commented
We're only using a model factory in one file:

https://github.com/statamic/cms/blob/master/tests/Auth/Eloquent/EloquentUserTest.php#L101
https://github.com/statamic/cms/blob/master/tests/Auth/Eloquent/EloquentUserTest.php#L34-L41

We can probably just avoid using a model factory there and then get rid of the dependency.

2020-09-27 21:31 UTC, edalzell commented
Having some difficulty w/ fake user generation and non-unique `id`s

2020-10-01 17:25 UTC, mrmonat commented
I have opened a PR on your fork which fixes all the failing tests by not using laravel/legacy-factories but instead using Faker on the failing test directly. 

PR: https://github.com/edalzell/cms/pull/415

2020-10-01 23:37 UTC, edalzell commented
@jasonvarga I tried to get the tests running properly but GH actions befuddle me. I _think_ I have it set up so that L8 won't run w/ PHP 7.2, but now L8 isn't running at all.

2020-10-02 07:06 UTC, mrmonat commented
You have merged my PR only "half". You use "WithFaker" Trait in the Test now without using it.

2020-10-02 17:01 UTC, jasonvarga requested changes

2020-10-02 17:01 UTC, jasonvarga commented on tests/Auth/Eloquent/EloquentUserTest.php
> +    private $num = 0;
See my other comment. This property can be removed.

2020-10-05 15:49 UTC, merged

2020-10-05 15:49 UTC, jasonvarga commented
Thanks very much for this. 🎉  @mrmonat, too.