Improve query params manipulation
statamic/cms pull request #2638
Opened 2020-10-12 09:37 UTC by piljac1

**This pull request adds the following:**

1. The `current_full_url` cascade contextual variable which behaves the same as `current_url` but includes query parameters
2. An `add_query_parameter` modifier which adds the specified key/value pair to the URL as a valid query param
3. A `set_query_parameter` modifier which adds the specified key/value pair to the URL (or updates the matching key) as a valid query param
4. A `remove_query_parameter` modifier which removes the query param matching the specified key (if it exists) from the URL

**Usage**
```html
{{ url add_query_parameter="category|dogs" }}
{{ url set_query_parameter="category|dogs" }}
{{ url remove_query_parameter="category" }}

{{ url add_query_parameter:category:dogs }}
{{ url set_query_parameter:category:dogs }}
{{ url remove_query_parameter:category }}
```

**Todo list**
- [x] Add a `current_full_url` cascade contextual variable which returns the complete URL
- [x] Add an `add_query_parameter` modifier which adds the specified key/value pair to the URL as a valid query param
- [x] Add a `set_query_parameter`  which adds the specified key/value pair to the URL (or updates the matching key) as a valid query param
- [x] Add a `remove_query_parameter`  which removes the query param matching the specified key (if it exists) from the URL
- [ ] Make sure to preserve the anchor tag if it was specified

2020-10-12 20:42 UTC, jasonvarga requested changes
This is great.

If you could apply the simple style changes listed here, that would be great.

https://github.styleci.io/analyses/ZlMv6b?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2020-10-12 22:35 UTC, piljac1 commented
> This is great.
> 
> If you could apply the simple style changes listed here, that would be great.
> 
> https://github.styleci.io/analyses/ZlMv6b?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Done !

2020-10-13 20:12 UTC, jasonvarga approved these changes

2020-10-13 20:14 UTC, merged

2020-10-13 20:15 UTC, jasonvarga commented
Awesome, thanks!