Fix 500 errors for an empty search string
statamic/cms pull request #2974
Opened 2020-12-04 22:07 UTC by jelleroorda

Fixes #2971, this time staying inside the `Statamic\Search\Comb` namespace.

2020-12-04 22:45 UTC, jasonvarga requested changes
Thanks, an even better place than what I suggested in the other PR.

2020-12-04 22:45 UTC, jasonvarga commented on src/Search/Comb/Index.php
> +        } catch (NoResultsFound | NotEnoughCharacters | NoQuery $e) {
This class needs to be imported.

2020-12-05 14:22 UTC, jelleroorda commented on src/Search/Comb/Index.php
> +        } catch (NoResultsFound | NotEnoughCharacters | NoQuery $e) {
Good catch I've updated the PR.

2020-12-07 14:55 UTC, merged

2020-12-07 14:55 UTC, jasonvarga commented
Thanks!