update method signatures
statamic/cms pull request #3012
Opened 2020-12-13 04:14 UTC by edalzell

The method were missing the return type hint so intellisense was complaining.

2020-12-14 15:26 UTC, jasonvarga requested changes
It should be `@method static returnvalue method(args)`

2020-12-15 00:30 UTC, edalzell commented
Made those changes @jasonvarga

2020-12-15 18:46 UTC, jasonvarga requested changes

2020-12-15 18:46 UTC, jasonvarga commented on src/Facades/Term.php
> + * @method static Term make(string $slug = null)
This should be `TermContract`.

2020-12-16 15:29 UTC, jasonvarga approved these changes

2020-12-16 15:30 UTC, merged