Fix for #1776
statamic/cms pull request #3043
Opened 2020-12-21 15:18 UTC by matthewbdaly

This pull request implements a fix for issue #1776 by:

* Adding a `url()` method to `Statamic\Taxonomies\Taxonomy` so as to enable getting the URL for use in the breadcrumbs
* Pulling in the existing trait `Statamic\Data\ContainsSupplementalData` so that taxonomy can be set as current

2021-01-12 21:03 UTC, jasonvarga requested changes
Thank you for the PR and sorry about the delay.

The url addition is a nice start, but doesn't really do anything. If you try to use `{{ url }}` in your template like the issue showed, it's null (so falls back to the current page's url).
That's because `url` needs to be added to `augmentedArrayData` in the `Taxonomy` class.

Also, the `url` isn't just the `uri`. If you look at the `Routable` class, you can see that `url` is the relative version of `absoluteUrl`, which has the entire site's domain. Since taxonomies themselves aren't localizable, they don't have "a site". Instead, it's fine for now if it just gets the current site (`Site::current()`).

If that's all too overwhelming, let us know and we can tackle it instead.

2021-01-12 23:34 UTC, matthewbdaly commented
Thanks for your response.

I've pushed up the requested changes. However, something is slightly off in the URL generated now.

The site on which I experienced this issue  has a collection called `recipes`, with a taxonomy for 'diets', and under that a taxonomy item for `vegan`. When generating the URL for the taxonomy, it should be `/recipes/diets`, but instead it's showing `/recipes/diets/default`.

2021-01-13 18:02 UTC, jasonvarga commented
Sorry I guess I wasn't clear. When I said this

> you can see that url is the relative version of absoluteUrl, which has the entire site's domain

I meant, it _contains_ the entire site's domain. Not that it is _just_ the site's domain.

Like if you have your site configured to be `/french/`,
then the `uri` would be `/recipes/diets`
the `absoluteUrl` would be `http://yoursite.com/french/recipes/diets`
and the `url` would be `/french/recipes/diets`.

2021-01-17 22:25 UTC, matthewbdaly commented
OK, what I've done is amended it to pick up the collection's `url`, and then put the taxonomy's `uri` on the end of that.

For the site I built, that appears to work - as noted above, I'm using the collection `recipes`, taxonomy `diets`, and term `recipes`, and it seems to consistently output the breadcrumbs for that as `/recipes/diets`.

2021-03-30 20:00 UTC, jasonvarga commented
Closing in favor of #3448

2021-03-30 20:00 UTC, closed without merging