Remove route model binding for users
statamic/cms pull request #3088
Opened 2021-01-08 20:28 UTC by damcclean

This pull request resolves #2316, where issues crop up in existing Laravel apps if people are using route model binding to bind to their `User` model.

This PR just straight out removes the route model binding and replaces it with a lookup in the controllers where it is referenced with `Entry::find($id)`.

While working on this PR, I've also found posts on the Discord by some developers complaining that Statamic's route model binding is a bit generic and can cause issues if used side by side on an existing Laravel app. I'm happy to make any changes to any of the other route model binding stuff if that's something you'd like me to do.

Let me know if you have anything you'd like me to change.

2021-01-08 21:15 UTC, damcclean commented
Instead of removing route model binding entirely, maybe we could just rename the route model binds to being Statamic specific, like `statamic_user`, etc which would resolve any Statamic binding issues. Feel free to decline this PR if you'd like me to do that instead.

(thanks @edalzell for that idea)

2021-01-11 15:47 UTC, riasvdv commented
To be functionally the same as route model binding you need to do `User::findOrFail($id)`

2021-01-11 19:52 UTC, damcclean commented
> To be functionally the same as route model binding you need to do `User::findOrFail($id)`

Ah, good point! The only issue is... there's no `findOrFail` method on the UserRepository, [see here](https://github.com/statamic/cms/blob/3.0/src/Stache/Repositories/UserRepository.php#L39).

2021-01-11 19:56 UTC, edalzell commented
Also see here: https://github.com/statamic/cms/pull/3055

2021-01-12 16:36 UTC, jasonvarga requested changes
404s need to be thrown when the user in the url doesn't exist. You can copy the logic that you removed from the service provider.

2021-01-12 17:17 UTC, damcclean commented
> 404s need to be thrown when the user in the url doesn't exist. You can copy the logic that you removed from the service provider.

Added the `throw_unless` to the controllers.

2021-01-12 19:21 UTC, jasonvarga requested changes
Either remove the messages from the exceptions, or make sure you're passing the handle in from the route argument.

Right now since you're using `$user = User::find($user)` before new-ing up the exception, the message will be `User [] not found.` but it should be `User [whatever] not found.`

Since you don't ever see the exception messages, it's probably fine to just remove them.

2021-01-12 19:34 UTC, damcclean commented
> Either remove the messages from the exceptions, or make sure you're passing the handle in from the route argument.
> 
> Right now since you're using `$user = User::find($user)` before new-ing up the exception, the message will be `User [] not found.` but it should be `User [whatever] not found.`
> 
> Since you don't ever see the exception messages, it's probably fine to just remove them.

I've removed the exception messages.

2021-01-12 20:48 UTC, jasonvarga approved these changes

2021-01-12 20:48 UTC, merged