add `ray` modifier
statamic/cms pull request #3137
Opened 2021-01-21 00:13 UTC by edalzell

Add support for Laravel Ray via the `ray` modifier.

Use like `dump`, for example, `{{ foo | ray }}`

2021-01-21 00:22 UTC, jasonvarga requested changes

2021-01-21 00:22 UTC, jasonvarga commented on src/Modifiers/CoreModifiers.php
> +        ray($value);
Return the `$value` so you can continue chaining modifiers.

2021-01-21 07:22 UTC, damcclean commented
I've not tested this PR out but maybe it would be a good idea to throw an exception if the Ray package isn't actually installed?

2021-01-21 08:32 UTC, riasvdv commented
Probably better to just check if the Ray class exists, and if not return the value so the modifier does nothing, wouldn't want it to crash just because you forgot a ray call somewhere

2021-01-21 15:04 UTC, jasonvarga commented
A counter argument - if you add `| ray` to something and it does nothing, you might be thinking you're dumping in the wrong place. But maybe you just forgot to install it.

2021-01-25 15:33 UTC, jasonvarga approved these changes

2021-01-25 15:33 UTC, merged

2021-01-25 15:49 UTC, freekmurze commented
Thank you! I'm honoured that support for Ray is now included by default in Statamic ❤️