#3241 - Adds &nbsp's for each paragraph rather than the last one
statamic/cms pull request #3303
Opened 2021-02-24 17:41 UTC by berdjabrahamian

Fixes issue #3241

Before
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus orci a turpis vestibulum ornare.</p><p>Pellentesque interdum at odio ut tristique. Quisque in dui non turpis eleifend dignissim.</p><p>Etiam ultricies sem massa, imperdiet lobortis velit luctus eu. Morbi bibendum tortor vel ultricies&nbsp;tempor.</p>
```

After
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus orci a turpis vestibulum&nbsp;ornare.</p><p>Pellentesque interdum at odio ut tristique. Quisque in dui non turpis eleifend&nbsp;dignissim.</p><p>Etiam ultricies sem massa, imperdiet lobortis velit luctus eu. Morbi bibendum tortor vel ultricies&nbsp;tempor.</p>
```

However, it doesnt take into consideration the params. Will push an update to add support for that.

2021-02-24 23:59 UTC, duncanmcclean commented
Hey! From the looks of things, doesn't look your text to close the issue will work. Would you mind re-wording to `Closes #x` instead, that should work!

2021-02-26 16:33 UTC, berdjabrahamian commented
Updated widont completely to utilize params as well - since we have noted it in the docs - as well as added tests for different variations.

2021-02-26 17:26 UTC, berdjabrahamian commented
Im not sure why the tests are failing and what im missing

2021-03-01 17:45 UTC, jasonvarga commented
I think it the `EOD`s needed their indentation removed. I updated that for you. Tests are running...

2021-03-01 18:11 UTC, jasonvarga requested changes
A few small changes, but otherwise this is wonderful, thanks!

2021-03-01 18:11 UTC, jasonvarga commented on src/Support/Str.php
> +            return $value;
Can you just `return preg_replace_callback(...)`?

2021-03-01 18:11 UTC, jasonvarga commented on tests/Modifiers/WidontTest.php
> +    public function modify($value, $params = 1)
Can you change this to `$params = []` so it tests no param by default?

2021-03-23 19:02 UTC, jasonvarga approved these changes

2021-03-23 19:53 UTC, merged

2021-03-23 19:54 UTC, jasonvarga commented
Thanks, very nice!