Default to 50-50 for Augmented 'focusCss' value on Assets
statamic/cms pull request #3340
Opened 2021-03-05 18:02 UTC by duncanmcclean

This PR fixes #3327 by defaulting to 50-50, instead of returning an empty output.

## Steps to test
1. Create assets field
2. Add a sample asset to that field (one without a focal point set)
3. Loop through items in asset field, with following template code:

```
{{ big_image }}
    <div class="w-full" style="height: 200px; background-image: url('{{ url }}'); background-position: {{ focus_css }};"></div>
{{ /big_image }}
```

4. `focus_css` will then be empty. This fix will make that `50% 50%` instead.

2021-03-05 19:34 UTC, jasonvarga requested changes

2021-03-05 19:34 UTC, jasonvarga commented on tests/Assets/AssetTest.php
> +            ->set('focus', '75% 25%');
This should be `75-25`

2021-03-05 19:37 UTC, duncanmcclean commented on tests/Assets/AssetTest.php
> +            ->set('focus', '75% 25%');
Good catch! Resolved.

2021-03-19 14:27 UTC, jasonvarga approved these changes

2021-03-19 14:30 UTC, jasonvarga commented
Since we're always providing `focus_css`, I thought we should probably also be providing `focus`. I made _that_ fall back to `50-50-1`.

2021-03-19 14:43 UTC, merged