Make structure entry eager loading conditional (take 2)
statamic/cms pull request #3540
Opened 2021-04-16 14:03 UTC by arthurperton

Fixes #3334, adding the suggested `withEntries()` method to `Tree`.

The `TreeBuilder` calls this method. So at least the `StructurePagesController`, `NavigationController` and the `Structure` tag will leverage eager loading. And viewing a page on the front-end just loads the one entry (no eager loading; default behaviour).

It also gets rid of the `structure-page-entries` Blink stores for entries. `Page` and `Tree` share the same Blink store now.

2021-04-16 15:10 UTC, arthurperton commented
💩 I'll have to fix those later

2021-06-21 22:45 UTC, jasonvarga requested changes
I know it's my fault for letting this PR sit here. But If you could merge 3.1 back into this, resolve the conflicts, and get it working again, I'll try to get it merged. Thanks! 🤗

2021-06-30 20:14 UTC, jasonvarga approved these changes

2021-06-30 20:14 UTC, jasonvarga commented
🚀

2021-06-30 20:15 UTC, merged