Leverage Laravel to determine secure connection
statamic/cms pull request #3695
Opened 2021-05-12 11:23 UTC by CiiDyR

We are running statamic behind reverse a reverse proxy to terminate SSL for us before our docker container handles the request.
Currently this makes the URL Facade return a rather useless URL when calling `getSiteUrl`.

Instead of writing custom logic to determine if the original request was https (X-Forwarded-Proto or similar) I think it would make sense to just use Laravels request class to determine this.

2021-05-12 14:59 UTC, jasonvarga commented
Awesome. That code was leftover from v2. Nice find.

2021-05-12 15:18 UTC, CiiDyR commented
I guess we might as well fully leverage what Laravel offers. If I am not mistaken `$request->root()` should be identical to what would be built in `getSiteUrl()` anyway

2021-05-12 15:27 UTC, jasonvarga commented
Yes, maybe. But it should end with a `/`, at least. I see that `root()` wouldn't.

2021-05-12 15:43 UTC, CiiDyR commented
I'll take another look at it later. We can at least drop the tenary operator in favor of `getScheme()`.
Maybe that's preferred to just appending a `/`?

2021-05-13 09:10 UTC, CiiDyR commented
Took a look at `root()`. Didn't change one bit from 6.x to 8.x. Went with `Str::ensureRight()` just to have it a little more robust.

Instead of Laravel's `root()` we could also use `getSchemeAndHttpHost()` from Symfony which is pretty much identical.

Maybe @jasonvarga can review?

2021-05-13 13:33 UTC, jasonvarga requested changes

2021-05-13 13:33 UTC, jasonvarga commented on src/Facades/Endpoint/URL.php
> +        return Str::ensureRight($rootUrl);
You didn't pass the slash.

2021-05-16 13:14 UTC, duncanmcclean commented
Just a quick thing, looks like the Style CI checks are failing.. https://github.styleci.io/analyses/BM4g7V?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2021-05-20 20:20 UTC, jasonvarga approved these changes

2021-05-20 20:22 UTC, merged