Allow Addon FieldTypes to be usable on Forms
statamic/cms pull request #3772
Opened 2021-05-26 09:21 UTC by michaelr0

Hey there,

This aims to allow FieldTypes to use a parameter or method to specify that they can be used on Forms.
This way addon's can be created to add FieldTypes that can be used on Form Blueprints.

An addon FieldType could then appear as a selectable field when editing a form's blueprint, either by using one of the below methods.

```php
class MyAwesomeField extends Fieldtype
{
    protected $supportedInForms = true;
```

```php
class MyAwesomeField extends Fieldtype
{
    protected function supportedInForms(){
       return true; // Or various logic.
   }
```

Frontend output would need to be handled by either the end developer or the addon developer, but that is to be expected I suppose?

Open to ideas, let me know what you think.

Thanks.

2021-05-26 16:47 UTC, jasonvarga commented
Just so you know, you could already use any fieldtypes you want. It just doesn't show in the UI.

2021-05-26 21:13 UTC, michaelr0 commented
> Just so you know, you could already use any fieldtypes you want. It just doesn't show in the UI.

Hi Jason, 

Thanks, I suppose what this aims to do is to allow add-on' fieldtypes the option to be able to appear on the form blueprint GUI, said add-on would probably need to include the needed front-end logic.

Thanks.

2021-06-10 17:05 UTC, jasonvarga requested changes

2021-06-10 17:05 UTC, jasonvarga commented on src/Fields/Fieldtype.php
> +            'supportedInForms' => $this->supportedInForms(),
Let's get rid of this.

2021-06-10 17:05 UTC, jasonvarga commented on tests/Fields/FieldtypeTest.php
> +            'supportedInForms' => false,
Let's get rid of this.

2021-06-10 22:07 UTC, michaelr0 commented
Hi Jason,

Not a problem, I have made those changes and have enabled those fields by default.

Thanks

2021-06-17 15:10 UTC, jasonvarga commented
Thanks for this, it's being built upon in #3866

2021-06-17 15:10 UTC, closed without merging