Allow setting more Pusher options like host and port
statamic/cms pull request #3927
Opened 2021-06-29 21:18 UTC by okaufmann

Hi,

We'd like to use a custom pusher server hosted with https://github.com/beyondcode/laravel-websockets. For Example, to use https://statamic.com/addons/statamic/collaboration. 

To allow this, more pusher options are required to configure the Statamic Pusher instance.

This PR adds the ability to also configure the options `host`, `port` and `disableStats`.

2021-06-29 21:22 UTC, jackmcdade commented
Thanks for the PR! Curious why you chose to set one option inline with a default, but added `if` checks for the other two. Is there some kind of different behavior triggered by configuring it that way?

2021-06-29 22:57 UTC, okaufmann commented
I did't want to set an official Pusher host explicitly as a default and let the client library to choose the default host. This can only be achieved when i don't set it to null, if no custom host is provided.

Maybe this mechanis is only needed for the host, as the default port ist alway 443.

The basic idea behind this line is to not change anything for the most people that just want to use pusher.

2021-06-29 23:26 UTC, jasonvarga requested changes
I think it may be better to just allow you to add an array that'll get merged into the config.

Something like this in `config/broadcast.php`:

```php
'echo_options' => [
  'wsHost' => '...',
  'wsPort' => '...',
  'disableStats' => false
]
```

and in `Echo.js`:

```js
config = {
  broadcaster: 'pusher',
  // etc
  ...Statamic.$config.get('broadcasting.extra')
};

this.echo = new LaravelEcho(config);
```

Then, if someone wants to add other Pusher options like `wssPort`, `statsHost`, etc, we won't have to add support for each one. You can just plop whatever you want.

2021-06-29 23:50 UTC, okaufmann commented
Thanks for your fast review, Jason!

It would be great to use the same options out of `config/broadcast.php` as a standard Laravel project would use though...

When we add a separate option key to just add more options to the Statamic Echo Client instance, we would have something like this:

```php
<?php

return [

    // ...

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'encrypted' => env('PUSHER_ENCRYPTED', true),
                'host' => env('PUSHER_HOST', '127.0.0.1'),
                'port' => env('PUSHER_PORT', 6001),
            ],
            'echo_options' => [
                'wsHost' => env('PUSHER_HOST', '127.0.0.1'),
                'wsPort' => env('PUSHER_PORT', 6001),
                'disableStats' => false,
            ],
        ],

    // ...

```

Let me think about this, I get back to this PR when I have a more flexible solution.

2021-06-29 23:52 UTC, jasonvarga commented
Sure, but you could reference those config options:

```php
'echo_options' => [
  'wsHost' => config('broadcasting.connections.pusher.options.host'),
  'wsPort' => config('broadcasting.connections.pusher.options.port'),
  'disableStats' => false
]
```

2021-06-29 23:56 UTC, jasonvarga commented
I take that back, I don't think you can because it's the same file. You could use a variable though:


```php
'connections' => [
    'pusher' => [
        'options' => [
            'host' => $pusherHost = env('PUSHER_HOST', '127.0.0.1'),
            'port' => $pusherPort = env('PUSHER_PORT', 6001),
        ],
    ]
],

'echo_options' => [
    'wsHost' => $pusherHost,
    'wsPort' => $pusherPort,
    'disableStats' => false
]
```

2021-07-14 19:08 UTC, jasonvarga commented
Closing this for now. Feel free to re-open if/when you decide to implement the requested changes.

2021-07-14 19:08 UTC, closed without merging

2021-07-14 19:31 UTC, okaufmann commented
I will 👍