Throw a helpful exception if a referenced blueprint does not exist
statamic/cms pull request #3977
Opened 2021-07-08 19:46 UTC by duncanmcclean

This pull request adds a helpful exception that'll be thrown if a specified blueprint does not exist. I've added an Ignition solution to the exception that'll suggest any blueprints close to the specified name (done the same was as in the [`CollectionNotFoundException`](https://github.com/statamic/cms/blob/3.1/src/Exceptions/CollectionNotFoundException.php))

Closes #3920

## Ignition Exception

![image](https://user-images.githubusercontent.com/19637309/124981388-6b1aca00-e02d-11eb-9805-3babbda3cfe8.png)

2021-07-08 19:47 UTC, jasonvarga requested changes
Can we call it `BlueprintNotFoundException`? We use the "not found" pattern all over. You even use it in the message. 😄

2021-07-08 19:49 UTC, jasonvarga requested changes

2021-07-08 19:49 UTC, jasonvarga commented on src/Exceptions/BlueprintNotFoundException.php
> +    protected function getSuggestedCollection()
`getSuggestedBlueprint` ?

2021-07-08 19:50 UTC, duncanmcclean commented
> Can we call it `BlueprintNotFoundException`? We use the "not found" pattern all over. You even use it in the message. 😄

One step ahead of you, see dd72ea274

2021-07-08 19:50 UTC, duncanmcclean commented on src/Exceptions/BlueprintNotFoundException.php
> +    protected function getSuggestedCollection()
Whoops! Changed.

2021-07-08 20:41 UTC, jasonvarga requested changes

2021-07-08 20:41 UTC, jasonvarga commented on src/Exceptions/BlueprintNotFoundException.php
> +        $description = ($suggestedCollection = $this->getSuggestedBlueprint())
Nitpick, it still says collection.

2021-07-08 20:48 UTC, duncanmcclean commented on src/Exceptions/BlueprintNotFoundException.php
> +        $description = ($suggestedCollection = $this->getSuggestedBlueprint())
Doh!

2021-07-15 16:28 UTC, jasonvarga commented
I don't know how helpful the suggestions are.

I renamed a blueprint in order to see the error.
Then the exception said `Did you mean user?` so I changed my entry to `blueprint: user`

Then I get this, which is probably even more confusing.

![image](https://user-images.githubusercontent.com/105211/125823340-d517bc60-9451-4264-b4ad-1445d5253c8a.png)

If we want to provide suggestions, maybe we should pass in the namespace so it only suggests ones that would work.

2021-07-15 16:30 UTC, jasonvarga commented
It's an easy fix, I'll just do it 👍

2021-07-19 18:53 UTC, jasonvarga approved these changes

2021-07-19 18:53 UTC, merged