Check permissions for Telescope
statamic/cms pull request #4075
Opened 2021-07-31 05:34 UTC by michaelr0

Checks if the user can access Telescope, will only add the link if they can.
Also changes the check from telescope.enabled to instead look for the existance of the route and changes the link to be returned from route('telescope'), so that it is functionally the same as https://github.com/statamic/cms/pull/4074

2021-08-01 00:38 UTC, michaelr0 commented
Looks like Telescope has a new logo, https://github.com/laravel/telescope/blob/4.x/art/logo.svg but it also happens to include the label in it.

2021-08-02 22:37 UTC, jasonvarga requested changes
If you're not in production, anyone can access telescope. `$user->can('viewTelescope')`alone isn't enough. The icon disappears, but if I hit the route directly, I can still access it.

I think changing to `&& Laravel\Telescope\Telescope::check(request())` will do.

See https://github.com/laravel/telescope/blob/148733ef406a7e691ff2aeb7cab0812b2c66c089/src/TelescopeApplicationServiceProvider.php#L29-L32

2021-08-02 23:11 UTC, michaelr0 commented
No worries, I've changed `$user->can('viewTelescope')` to `\Laravel\Telescope\Telescope::check(request())`

2021-08-03 00:52 UTC, jasonvarga approved these changes

2021-08-03 00:52 UTC, merged