Remove dashboard nav when widgets are empty
statamic/cms pull request #4226
Opened 2021-09-06 21:45 UTC by jbreuer95

Just an idea, it is mostly personal preference.
I would like to be able te remove the dashboard link.
This way when there are no widgets, so no content for the dashboard and its not the default route it can be omitted.

It can also be an extra config option but that feels like config bloat.

2021-09-06 22:25 UTC, jasonvarga commented
What happens when you log in and you land on the dashboard?

2021-09-07 07:25 UTC, jbreuer95 commented
When `statamic.cp.start_page` is set to dashboard it will still show

2021-09-08 14:43 UTC, jasonvarga requested changes
The nav sits too far up when the dashboard item is removed.

2021-09-15 13:26 UTC, jackmcdade commented
Closed in favor of https://github.com/statamic/cms/pull/4266.

2021-09-15 13:26 UTC, closed without merging

2021-09-15 19:54 UTC, jbreuer95 commented
@jackmcdade Thank you :)