Add min and max file size validation rules for assets
statamic/cms pull request #4980
Opened 2021-12-28 12:49 UTC by arthurperton

This fixes #4217 as requested. 

Careful though, this is a breaking change: before the `min` and `max` rules would validate the _number of assets_ and now they check the file size.

I'm thinking should we use custom names for these rules to differentiate between the two?

2022-01-03 15:02 UTC, jasonvarga requested changes
> I'm thinking should we use custom names for these rules to differentiate between the two?

Agreed.

Let's keep `min`/`max` as validating number of assets.

Let's validate file size using... `min_filesize`, `max_filesize`  ...?

2022-01-03 16:06 UTC, arthurperton commented
> > I'm thinking should we use custom names for these rules to differentiate between the two?
> 
> Agreed.
> 
> Let's keep `min`/`max` as validating number of assets.
> 
> Let's validate file size using... `min_filesize`, `max_filesize` ...?

Yes I like those, nice and clear. There should be a note in the docs about this probably, because this is not Laravelish?

2022-01-03 16:29 UTC, jasonvarga commented
Yes we can add those to the docs somewhere.

Also, we could add them to the blueprint builder. https://github.com/statamic/cms/blob/3.2/resources/js/components/field-validation/Rules.js

2022-01-05 16:13 UTC, jasonvarga approved these changes
Works really well, thank you!

The only little thing is that if you have an assets field that allows more than one to be selected, the validation message doesn't really tell you which asset is the problem.

This is fine for now though. We could improve on this later.

2022-01-05 16:14 UTC, merged

2022-01-15 17:53 UTC, sunscreem commented
@jasonvarga Just an FYI here.

I had a weird one on this. Somehow I ended up with a null validation rule on one of my assets:

```
sections:
  main:
    display: Main
    fields:
      -
        handle: donation_form_pdf
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Donation Form PDF'
          type: assets
          icon: assets
          listable: hidden
          container: spaces
          validate:
            - null
            - 'mimes:pdf'
          width: 33
```

I'm not sure how that happened but it hadn't caused any issues until I updated Statamic to the version with this fix, where it broke my graphQl queries. 

I took a dive into the source to figure this one out, and I'm fairly sure it was a dumb mistake by me, but thought I'd pop the comment here just in case it flags up for anyone else.

2022-01-16 17:38 UTC, jasonvarga commented
Thanks for the heads up, but I don't think this PR specifically would have had any effect over what options made it into that array.