Delete term references
statamic/cms pull request #4989
Opened 2021-12-29 21:06 UTC by arthurperton

Fixes #3590 and fixes #3299. 

Surprisingly easy, leveraging the power of the ReferenceUpdater classes. It only took 3 minor adjustments to the existing code and a new Listener. And it all works great in the manual tests, solving both issues.

This obviously deserves more (unit) testing, but before putting time in that I'd like to know if you guys are okay with this solution. Any feedback?

Thanks!

2022-01-05 21:32 UTC, jasonvarga requested changes
There is test coverage for this stuff.
Could you add a `DelteTermReferencesTest`?
The others are in `tests/Listeners/UpdateTermReferencesTest.php`

2022-01-06 16:44 UTC, jesseleite commented
Haven't pulled it down, but looks good to me! I'm with Jason about adding a `DeleteTermReferencesTest` case is all 👍

2022-01-06 16:49 UTC, jesseleite commented
Haven't pulled it down, but other than adding a `DeleteTermReferencesTest`, it looks good to me 👍 

Also, maybe we should implement the same thing when deleting asset references? https://github.com/statamic/cms/blob/3.2/src/Listeners/UpdateAssetReferences.php

2022-01-07 11:10 UTC, arthurperton commented
Thanks for the confirmation guys, I'll put the time in then to add the tests. And I'm okay with handling asset deletions too in this PR, good idea 👍🏻

2022-01-07 15:15 UTC, arthurperton commented
Okay, good to go!

I also added tests. For the basic cases only, not all the nested variants that are in the `UpdateXxReferencesTest` classes. Since almost all code is shared, that seems a little redundant.

2022-03-10 19:43 UTC, jasonvarga requested changes
Sorry for the delay.

I think there should be some tests around deleting assets within bards.
You've updated the implementation so there should be some test coverage.

- [x] it_deletes_asset_references_in_bard_field
  - test should include an image node and a link node 
- [ ] it_deletes_asset_references_in_bard_field_when_saved_as_html
  - test should include an img and an anchor

2022-03-11 10:04 UTC, arthurperton commented
Ah yes. Makes me wonder what to do when an asset is deleted. Should the image node have it `src` set to `null`, or should the entire node be deleted? For links, it is possible to leave the text and remove the link. Or keep the link and set the `href` to `null`. Removing the entire link with text seems a bit harsh.

I am having a hard time to decide. On the one hand it is no use to leave broken images / links in your content. On the other hand, when the node gets deleted, you also loose any associated information like the alt text, link title, etc. For the image node you won't even know any image was there...

2022-03-11 15:40 UTC, jasonvarga commented
I'm not sure either.

Maybe just don't do anything? It's going to be broken either way.

2022-03-13 14:11 UTC, arthurperton commented
I agree, it’s broken either way. And leaving the image / link untouched will leave information on what asset was supposed to be there, which will help in fixing the content. I think it is a good idea, I will implement (and test) it like that.

2022-08-19 15:10 UTC, jasonvarga commented
Superseded by #6504

2022-08-19 15:10 UTC, closed without merging

2022-08-19 15:11 UTC, jesseleite commented
Shoot, I guess I totally forgot about this one when I PR'd https://github.com/statamic/cms/pull/6504 recently, I'm sorry @arthurperton!