Update scheduled status when it should
statamic/cms pull request #5089
Opened 2022-01-18 20:12 UTC by aerni

This PR takes another stab at updating the `scheduled` status of entries when the date is in the past. As discussed in this closed PR https://github.com/statamic/cms/pull/4653.

Hope this is going in the right direction now. At least it feels better than before.

2022-01-19 05:10 UTC, jesseleite commented
@jasonvarga, Does this `status` index conflict with the [$entry->status() method](https://github.com/statamic/cms/blob/3.2/src/Entries/Entry.php#L559-L580) available on entries?

2022-01-20 16:33 UTC, jasonvarga commented
This index would be populated with exactly that - $entry->status() values.

2022-03-04 16:31 UTC, jasonvarga commented
FYI the delay on this is because it only solves the issue for the Stache. If you're using Eloquent for example, it won't have any effect. We wanted to think through it a little more.

But if you're wanting to use it, you can use a [composer patch](https://rias.be/blog/using-composer-patches).

2022-03-04 16:58 UTC, edalzell commented
> FYI the delay on this is because it only solves the issue for the Stache. If you're using Eloquent for example, it won't have any effect. We wanted to think through it a little more.
> 
> But if you're wanting to use it, you can use a [composer patch](https://rias.be/blog/using-composer-patches).

If you're using eloquent, aren't all the queries done "live" so that the future posts would get captured by the usual query? i.e. this problem doesn't exist w the Eloquent driver?

2022-03-04 19:28 UTC, jasonvarga commented
The `status` is still just sitting in a column. Something needs to update it.

I think the ideal solution would be to scrap the dedicated `status` value, and instead when you want to query for "published" entries, you would just do a more explicit query.

The `status` value takes into account all the scenarios - includes public/private future/past settings on the collection, etc.

Instead of doing `->where('status', 'published')`, you'd do `->where('published', true)->whereDate('date', '<=', now())`, etc. That way you're only ever querying values that wouldn't "become outdated".

This would be a much more far-reaching change though.

2022-03-04 19:34 UTC, aerni commented
Are you saying that this can't be implemented without breaking changes?

2022-03-04 20:07 UTC, jasonvarga commented
I think this PR will end getting merged and we'll have some alternate solution for Eloquent. But we want to have an idea before we push the button.

2022-05-16 06:28 UTC, jasonvarga commented
Could you target 3.3 and merge 3.3 into this?

2022-11-10 09:43 UTC, Buffalom requested changes

2022-11-10 09:43 UTC, Buffalom commented on src/Stache/Indexes/Status.php
> +            return $value === 'scheduled' && $this->store->index('date')->get($id)->isPast();
This should include status `'published'` so expirable items (as in they are hidden starting at the given date) get updated to status `'expired'` as well. Something like this:

```php
return ($value === 'scheduled' || $value === 'published') && $this->store->index('date')->get($id)->isPast();
```

2022-11-10 09:43 UTC, Buffalom commented on src/Stache/Indexes/Status.php
> +            return $value === 'scheduled' && $this->store->index('date')->get($id)->isPast();
I've explained it in more detail in https://github.com/statamic/cms/issues/2217#issuecomment-1310014800.

2023-01-20 12:16 UTC, ryanmitchell commented
Maybe this is the solution you already discounted, but we could drop the status column in eloquent-driver and if the column is `status` simply do the alternative query you mentioned (`->where('published', true)->whereDate('date', '<=', now())`)

2023-03-09 18:33 UTC, jesseleite commented
This got mentioned again in Discord. Not sure @jasonvarga's current thoughts, but just a quick note that as this PR currently stands, it doesn't (yet) properly account for [all four status possibilities as documented here](https://statamic.dev/collections#date-behavior-and-published-status)...

![CleanShot 2023-03-09 at 13 30 51](https://user-images.githubusercontent.com/5187394/224121634-a68f3612-ff74-4095-83ed-f78332cb2e78.png)

2023-04-12 20:03 UTC, aerni commented
I was just dealing with some caching invalidation questions regarding entry listings that kind of ties into this issue. I think it would be pretty nice if there was an `EntryStatusChanged` event that triggers whenever a status changes. This way, we can programmatically clear the cache when needed instead of relying on a scheduled command.

2023-04-13 13:34 UTC, jasonvarga commented
That's what #5502 is essentially doing. You'd be able to see if the status is different.

2023-04-13 13:37 UTC, aerni commented
As far as I understand, that PR is only useable in existing events like `EntrySaved`. I'm talking about an event that triggers when an entry status changes without the users interaction to save an entry.

2023-04-13 13:39 UTC, jasonvarga commented
If we could tell when an entry's status changes without user interaction, then we wouldn't have this issue to begin with.

2023-04-13 13:41 UTC, aerni commented
Haha totally. What I'm trying to say. This PR here deals with stache invalidation. But there needs to be a way to ALSO invalidate the static cache when a status changes.

2023-04-13 13:51 UTC, jasonvarga commented
I'm with ya

2023-06-07 22:26 UTC, jasonvarga commented
Closing in favor of #8281. Give that a shot and see how it works for you.

2023-06-07 22:26 UTC, closed without merging