Refactor saveQuietly logic
statamic/cms pull request #6086
Opened 2022-05-25 06:49 UTC by ryanmitchell

This PR refactors the Entry saveQuietly logic to avoid the value being cached/saved across multiple calls. I've also increased test coverage to ensure that events are fired after an initial saveQuietly call.

Fixes: #5628

2022-05-26 14:04 UTC, jbreuer95 commented
Works for me :)

2022-05-26 14:09 UTC, ryanmitchell commented
Yep, I figured the best solution was to make sure it always had `withEvents: true` before it was stored to the cache. Happy to refactor if theres a better way :)

2022-05-26 14:09 UTC, jasonvarga commented
Nope! I like it. I'll give it a test in a bit.

2022-06-02 20:04 UTC, jasonvarga requested changes

2022-06-02 20:04 UTC, jasonvarga commented on tests/Data/Entries/EntryTest.php
> +
Actually, I just thought of something.

2022-06-02 20:11 UTC, ryanmitchell commented on tests/Data/Entries/EntryTest.php
> +
Ah of course. Good thinking.

2022-06-03 18:15 UTC, jasonvarga commented
I know it's not the best test, but it's something. And by manually testing Michael's repo I can confirm this fixes it.

2022-06-03 18:15 UTC, merged