Add Bard data modifiers
statamic/cms pull request #6226
Opened 2022-06-17 15:19 UTC by jacksleight

I'm leaving this as draft because I'm mostly interested in whether you think this might be a good addition? If so I will finish it off and add tests etc. It's something I was working on for one of my addons, but I think it could be a great addition to core.

This PR adds two new modifiers:

* `bard_text`: This traverses a bard value and returns a concatenated string of all text content
* `bard_items`: This traverses a bard value and returns a flat array of all nodes and marks

Bard values can either be the entire document, a list of nodes or an individual node.

When combined with the existing string and array modifiers these allow you to do some fairly powerful things. Particularly when it comes to extracting data from a Bard value. For example:

**Extract a text snippet (without the overhead of rendering and then stripping out the tags)**

```antlers
<meta name="description" content="{{ main_content | raw | bard_text | safe_truncate:90:… }}">
```

**Find the first heading to output in a listing elsewhere**

```antlers
<h2>{{ main_content | raw | bard_items | where:type:heading | first | bard_text }}</h2>
```

**Find and output a list of all links**

```antlers
<ul>
    {{ links = main_content | raw | bard_items | where:type:link }}
    {{ links }}
        <li><a href="{{ attrs:href }}">{{ content | bard_text }}</a></li>
    {{ /links }}
</ul>
```

The `raw` modifier has to be in there otherwise the Bard modifiers receive the rendered HTML and not the raw array data. It'd be nice if that wasn't necessary, something I was talking about in [this idea](https://github.com/statamic/ideas/issues/760).

This would also be really useful when implementing [footnotes](https://github.com/statamic/ideas/issues/713) in Bard. You could add a new inline node for the footnote anchors, and then use these modifiers to extract the list of footnotes and render them separately at the bottom of the page.

2022-06-17 19:14 UTC, edalzell commented on src/Modifiers/CoreModifiers.php
> +    public function bard_array($value)
`bardArray`

2022-06-17 19:15 UTC, edalzell commented on src/Modifiers/CoreModifiers.php
> +    public function bard_text($value)
`bardText`

2022-07-01 19:12 UTC, jasonvarga commented
> Let me know what you think.

If you were waiting for some approval before continuing, here it is! I have no problem with these sorts of modifiers being added. 👍 

I haven't reviewed how they work though. I'll leave that until you're ready for it to be reviewed.

2022-07-01 19:43 UTC, jacksleight commented
OK, great. I'll finish this off. 👍

2022-07-13 19:49 UTC, jasonvarga commented
I guess you can get the bard html by doing

```antlers
{{ bard_field | where:type:text | pluck:text | join('') }}
```

It would be nice to do `{{ bard_field | raw | bard_text }}` though.

(And of course be able to remove the `| raw` at some point)

2022-07-21 12:58 UTC, jacksleight commented
The best alternative to `bard_text` I’ve come up with is `bard_words`. Which I think works? It accurately describes what’s returned and I think it makes it clear that HTML isn’t included.

I’ve also added a _new_ `bard_text` modifier that does exactly what you expected the previous version to do, return the value without sets as rendered HTML. While that is already possible with an augmented value (like in your example), this is a bit simpler and particularly useful if you have some raw bard data, like a node that you’ve extracted using `bard_items`. I’ve added an image example above that uses this.

Do you think `bard_text` should accept a parameter that lets you toggle antlers parsing in the returned HTML, just like the fieldtype does for the original value?

Tests should be fine, but there seems to be a Slack issue.

2022-08-11 16:01 UTC, jacksleight commented
Could be outside the scope of this PR, but I’m using a “deep” version of the `bard_items` modifier locally, which will also traverse into sets (including replicator sets) and their values, finding all sets, nodes and marks all the way down. Handy if your top-level content field is some kind of page builder replicator, or you have words inside sets that you’d also like extracted.

https://gist.github.com/jacksleight/c54d95c0d5437fdd56218d85cc5e8e73

It is a bit more involved than the others and only works from PHP/Blade at the moment.

2022-08-11 16:08 UTC, jasonvarga requested changes
> The best alternative to bard_text I’ve come up with is bard_words. Which I think works? It accurately describes what’s returned and I think it makes it clear that HTML isn’t included.

`bard_words` makes sense to me 👍 

> I’ve also added a new bard_text modifier that does exactly what you expected the previous version to do, return the value without sets as rendered HTML. 

This is great too. But with the image example you provided, adding a bard_text modifier to output an `<img>` tag feels odd. Can we change it to `bard_html`?

> Do you think bard_text should accept a parameter that lets you toggle antlers parsing in the returned HTML, just like the fieldtype does for the original value?

Ideally I think it should "just work" based on whether you've defined `antlers` on the field or not.

> “deep” version of the bard_items modifier 

Sounds handy but let's leave it out for now. Especially since it can't work in Antlers.

2022-08-11 16:15 UTC, jacksleight commented
> Can we change it to `bard_html`?

No problem. Is there then an argument for renaming `bard_words` back to `bard_text`? `bard_html` gives you HTML, `bard_text` gives you plain text. Or am I overthinking this... probably. 😄

> Ideally I think it should "just work" based on whether you've defined antlers on the field or not.

So at the moment that isn't possible because without access to the `Value` object and it's `Fieldtype` there's no way to know whether antlers was set on the original field.

2022-08-11 16:17 UTC, jasonvarga commented
> So at the moment that isn't possible 

Then I guess yeah we'll need an argument. I'd it should _not_ use Antlers by default and then you opt into it.

2022-08-12 14:55 UTC, jacksleight commented
I've renamed `bard_text` to `bard_html`.

To add the antlers parsing I assume the best approach is copy what the Bard augmentor does in the `textValue()` method: create a new value object with the `antlers` option set, so that way it can be handled by the parser.

This works in the tests, but unfortunately doesn't work in a template. It looks like the parser doesn't like modifier chains returning value objects.

This outputs the value unparsed:

```antlers
{{ main_content | raw | bard_words:true }}
```

This errors with "Passed value cannot be an array":

```antlers
{{ main_content | raw | bard_words:true | safe_truncate:90 }}
```

But this does work:

```antlers
{{ test = main_content | raw | bard_words:true }}
{{ test }}
```

I'm not really sure how to resolve that.

2022-08-12 19:51 UTC, jasonvarga commented
Antlers modifier is a good idea. I guess you can revert your changes and just assume that'll be there. #6489

2022-08-13 10:18 UTC, jacksleight commented
Awesome! Commit reverted, I think that's everything. 👍

2022-08-15 18:03 UTC, jasonvarga commented
Sorry, somehow I overlooked this part of your comment the other day:

>  Is there then an argument for renaming `bard_words` back to `bard_text`? `bard_html` gives you HTML, `bard_text` gives you plain text.

This PR will end up with:
- `bard_items` giving you all the raw flattened ProseMirror stuff.
- `bard_html` giving you the html for all the text bits. Sets are excluded. You can use it a specific prosemirror node like an image and still get html back, too.
- `bard_text` giving you the plain text for all the text bits. Sets are excluded.

Makes sense to me!

2022-08-15 19:42 UTC, jacksleight commented
No worries, done!

2022-08-15 19:49 UTC, jacksleight commented
I might roll the functionality from the "deep" version into an addon. It'll work well alongside these modifiers but I'm thinking the use case might be a bit too specific for core.

2022-08-15 19:58 UTC, jasonvarga approved these changes

2022-08-15 19:59 UTC, merged