Added Vite tag
statamic/cms pull request #6271
Opened 2022-06-30 13:24 UTC by lokmanm

Since version [v9.19.0](https://github.com/laravel/framework/releases/tag/v9.19.0) of Laravel, Vite is now the default tool for bundling frontend assets.

In order for Statamic to fully migrate to this we will also have to change the `statamic/statamic` repo and remove the default Laravel Mix. Vite also plays nicely with Vue@2 which is required to build Fieldtypes or extending any frontend stuff.

If required I can also submit a PR to the docs for the new Vite tag.

More info on Vite at the Laravel [docs](https://laravel.com/docs/9.x/vite)

2022-06-30 13:37 UTC, jasonvarga requested changes

2022-06-30 13:37 UTC, jasonvarga commented on src/Tags/Vite.php
> +        if (! $src = $this->params->get('src')) {
It's my understanding that you may want to provide multiple sources.

For example on the Blade directive you could do this:

```blade
@vite(['resources/css/app.css', 'resources/js/app.js'])
```

So, you'll probably want to change this line to use `$this->params->explode('src')` so you can do `src="app.css|app.js"`

2022-06-30 13:41 UTC, jasonvarga requested changes

2022-06-30 13:41 UTC, jasonvarga commented on src/Tags/Vite.php
> +            throw new \Exception('Please provide a source file.');
Also, I don't think you _need_ to provide a source. Looking at the code, it doesn't seem to care if you pass it nothing.

2022-06-30 13:42 UTC, jasonvarga requested changes

2022-06-30 13:42 UTC, jasonvarga commented on src/Tags/Vite.php
> +        return app(LaravelVite::class)->__invoke($src);
You don't need to call `__invoke`. Just use brackets:

```suggestion
        return app(LaravelVite::class)($src);
```

2022-06-30 17:48 UTC, jesseleite commented
Ce PR a été vite! 🏎

2022-06-30 18:20 UTC, merged

2022-06-30 18:20 UTC, jasonvarga commented
Thanks!

2022-07-05 17:33 UTC, robdekort commented
I'm curious how the tag works.

2022-07-05 17:47 UTC, jasonvarga commented
Not sure about the inner workings of it. This just a wrapper around the Laravel feature. 

Looking at the code, at the moment the answer is no. But if you want `defer` to be added, you should ask over there.

https://github.com/laravel/framework/blob/3aaf3b2ff1b46bba71775cc41aca87572251ccfe/src/Illuminate/Foundation/Vite.php#L131-L134

It's also `type="module"` so maybe `defer` is not needed? That's beyond me.