Remove empty Bard paragraphs
statamic/cms pull request #6438
Opened 2022-08-03 19:43 UTC by aerni

This PR allows removing empty paragraphs from Bard fields. As discussed over here: https://github.com/statamic/ideas/issues/836
 
It introduces `remove_empty_paragraphs` with three options:

- `false`: Don't remove empty paragraphs
- `true`: Remove all empty paragraphs
- `trim`: Remove empty paragraphs at the top and the bottom

2022-08-03 20:57 UTC, jasonvarga requested changes
Could you add some tests?

Here's one that tests for the process method. You could add them under that.

https://github.com/statamic/cms/blob/7abbbe5d82ee2405245065d3a64efdc60f44ef5a/tests/Fieldtypes/BardTest.php#L388-L397

2022-08-03 21:01 UTC, aerni commented
Sure thing. Will do.

2022-08-04 15:01 UTC, jasonvarga approved these changes

2022-08-04 15:19 UTC, merged

2022-08-04 15:41 UTC, aerni commented
I just realized that this PR should be extended to also remove other empty types like headings. Will open a new PR to add this.

2022-08-04 16:18 UTC, jasonvarga commented
Good call. In that case we should change the config option you added to be more generic.

Remove empty elements?

2022-08-04 16:21 UTC, aerni commented
I like that. What should happen to empty lists (ul, ol)? Should they remain – leaving an empty bullet point – or be removed? I vote for removed. And empty sets should stay untouched.

2022-08-04 17:38 UTC, jasonvarga commented
Empty list items could be removed.

Empty sets should stay. Sometimes people use sets thats have no fields.

2022-08-04 17:57 UTC, aerni commented
Makes sense. So we could probably filter any type that isn't a set so that we don't have to maintain a huge list type's to remove when empty?

2022-08-04 18:36 UTC, aerni commented
Like what should happen if someone adds custom nodes? Should they also be removed when empty? Or should we only remove the nodes that ship with Statamic? 

We could also expose an option to define which nodes should be removed. Or add a static array of removable nodes, which a user could override in a service provider.

2022-08-04 18:42 UTC, jesseleite commented
@jasonvarga @aerni I realize this has been merged, but not yet tagged. What if we changed to...

```yaml
remove_empty_nodes:
  - paragraph
  - set
  - list
```

Or for trimming from top and bottom:

```yaml
trim_empty_nodes:
  - paragraph
  - set
  - list
```

...Having them explicitly define which nodes, like you said there Michael. Then if they want to remove/trim all node types, then pass a `true` boolean instead of array off nodes, ie) `trim_empty_nodes: true`

Thoughts?

2022-08-04 18:52 UTC, jasonvarga commented
This is getting way more complicated.

I think the original intention was to remove empty paragraphs because it's pretty easy to accidentally add them.

Adding extra list items, you'd see a bullet point.
Adding a blockquote, you'd get the quote styling.
A client would notice those.

If you need more control over the output, you can adjust the augmentation yourself.

2022-08-04 18:55 UTC, jesseleite commented
All good! Was just freestylin' off your suggestion...

>Good call. In that case we should change the config option you added to be more generic.
>
>Remove empty elements nodes?

😁

2022-08-04 18:56 UTC, aerni commented
I like your thoughts @jesseleite. But I think @jasonvarga is right haha. It's getting pretty complicated. The intention was to remove empty lines from bard that you might miss when writing an article. I checked through all the nodes and the only ones that don't render anything when they have no content is `heading` and `paragraph`. I suggest I simply extend the removal to those two types. But I'll still rename to `remove_empty_nodes` instead of `remove_empty_paragraphs`. Sounds good?