Add ability to add a blueprint to user groups
statamic/cms pull request #6506
Opened 2022-08-16 11:44 UTC by ryanmitchell

Ok be gentle as I've not worked with Vue a whole lot.

This PR adds the ability to modify the blueprint associated with a user group by adding some new routes, controllers and borrowing from the existing user blueprint approach for this. This would allow developers to add new fields to the groups, such as images, descriptions or whatever they want.

The only 'breaking' change I can see is adding `data()` to user groups and how that would affect eloquent - would love to hear your thoughts on this.

I will definitely have missed some things here, so marking as a draft for now. But I would value feedback at this stage.

2022-08-16 14:02 UTC, jasonvarga commented
Looks like a good addition to me. What more feedback were you looking for at the moment?

2022-08-16 14:06 UTC, ryanmitchell commented
That’s probably enough - just wanted to know if it was worth spending time on or if there was a reason it wasn’t there already. If there’s anything approach wise that looks wrong to you do let me know.

2022-08-16 14:06 UTC, jasonvarga requested changes

2022-08-16 14:06 UTC, jasonvarga commented on resources/js/components/user-groups/PublishForm.vue
> +    },
This needs to either be imported (`import ChangePassword from '../users/ChangePassword.vue'`) or just removed.

I'm guessing you copied the user form and missed removing this, so just remove it. 😄

2022-08-16 14:06 UTC, jasonvarga commented on resources/views/usergroups/edit.blade.php
> +    <user-publish-form
I don't think you meant to change to `user-publish-form`. You probably want to keep it as `user-group-publish-form`.

2022-08-16 14:07 UTC, jasonvarga commented
I think you're looking good! We haven't added the feature because no one wanted it yet. 🤷

2022-08-16 16:08 UTC, jasonvarga requested changes
Nice. Some things I noticed:

- [x] When you save the user group in the CP, the page title disappears.
- [x] When you save the user group in the CP, no custom field data is added to the file.
- [x] The blueprint should be added to the blueprint index. (/cp/fields/blueprints)
- [x] UserGroup's augmentedArrayData will probably need to be updated in order for the custom fields to be used in templates, #6505, etc.

2022-08-16 16:47 UTC, ryanmitchell commented
Thats really helpful thank you. Ive got them all fixed now.

2022-08-16 16:53 UTC, jasonvarga commented
I'm not sure why the tests are failing like that. I pulled the suite down locally, used the same PHP version and composer deps, and it all passes. 🤔

2022-08-16 16:55 UTC, ryanmitchell commented
Same! No idea what’s going on.

2022-08-17 07:43 UTC, ryanmitchell commented
@jasonvarga I cant figure this one out - everything passes locally using the same PHP and Laravel versions. The only thing I can notice thats different is the PHPunit version (9.5.21 locally versus 8.5.12). Maybe thats something to do with it?

2022-08-22 06:53 UTC, ryanmitchell commented
I've got all the tests passing by [specifying a min version of phpunit (8.5.23) on the PHP8 mockery action](https://github.com/statamic/cms/pull/6506/commits/9fe1aeaeed5bdab3c9349e0eb7f012fa0e8c8d11). Hope this is an acceptable solution.

2022-08-22 14:26 UTC, jasonvarga commented
Yeah I'm fine with that.

Looks like Orchestra requires 8.5.21 at a minimum, and 8.5.23 fixes a memory leak. Segfault seems like that's probably what it is. https://github.com/sebastianbergmann/phpunit/pull/4799

2023-06-21 22:13 UTC, jasonvarga commented
This is in a good spot. I think there's just one more thing to sort out.

The `handle`. Before this PR, you'd get red warning text if you try to change the handle, telling you that references won't be updated.

Now that handle becomes just a basic blueprint field, that feature is gone. I'm fine with putting that text just into the instructions, but then it's also possible to not include the handle field at all. In that case, the handle gets updated based on the title, which is awkward.

I'm thinking this:

- Leave off the handle field from the user group blueprint
- Explicitly add it in the "create" route
- Remove the handle-from-title fallback behavior - if you don't submit the handle, it just doesn't get updated.
- If you want to add a handle field, it becomes the user's responsibility to put instructions saying that it could mess things up.

(Just putting these as notes to ourselves to sort out. You don't need to do anything, @ryanmitchell)

2023-06-22 05:49 UTC, ryanmitchell commented
Thanks for the work on this. Its genuinely appreciated.

2023-06-22 15:39 UTC, jasonvarga commented
We can't inject the handle field directly after the title field, and adding a feature to do so would require a fair bit of work. So we're just going to remove the handle field. At least for now.

So, by default, the handle will get snake_cased from the title on creation.
If you want control over the handle, you can add it to your blueprint.

2023-06-22 17:27 UTC, jasonvarga approved these changes

2023-06-22 17:33 UTC, merged

2023-06-22 19:15 UTC, ryanmitchell commented
Amazing. So good to see this merge, thank you!