Show 'Create Blueprint' link on create entry dropdown
statamic/cms pull request #6813
Opened 2022-10-01 08:55 UTC by duncanmcclean

<img width="273" alt="image" src="https://user-images.githubusercontent.com/19637309/193401483-e611764c-8b8a-4202-9d67-5a3a179a9d17.png">

This pull request implements statamic/ideas#614. It adds a 'Create Blueprint' link onto the 'Create Entry' dropdown which lets you choose between available blueprints.

From what I've done so far, I wonder if there needs to be something to differentiate the 'Create Blueprint' button from the list of blueprints.. not quite sure how to do that (up for ideas) 🤔

2022-10-01 09:53 UTC, jacksleight commented
Nice! How about the divider from the actions menu?

![Screenshot 2022-10-01 at 10 52 36](https://user-images.githubusercontent.com/126740/193403760-60ce754f-e436-4183-b6c4-a0d8a90dd160.png)

2022-10-01 09:54 UTC, duncanmcclean commented
> Nice! How about the divider from the actions menu?

Ah, that's much better!

<img width="273" alt="image" src="https://user-images.githubusercontent.com/19637309/193403810-9a3d865f-2078-4c86-81b5-0ae0468b990f.png">

2022-10-03 18:47 UTC, jasonvarga requested changes
This will be something for @jackmcdade to weigh in on, but I find a bit inconsistent that you get the option to create a blueprint only if you already have multiple blueprints.

When you only have a single blueprint, the button isn't a dropdown.

![CleanShot 2022-10-03 at 14 43 27](https://user-images.githubusercontent.com/105211/193654245-ef15092a-7ffd-4205-a8ed-66f67caf5356.png)

That was a handy way of jumping right into the publish form.

But if you were to make it a dropdown button anyway... You'd have a button that says create entry, and then a dropdown menu option that also says create entry? A bit odd.


Maybe it could be one of those split buttons where the main part is just "create entry" and then the caret triggers the dropdown. But then it'd be different from the multiple blueprint button state.

This is something that'll need some UX thought.

2022-10-13 19:16 UTC, jasonvarga commented
Closing this as it's not really high priority and needs more thinking. Feel free to continue the discussion on [the original idea issue](https://github.com/statamic/ideas/issues/614). Thanks!

2022-10-13 19:16 UTC, closed without merging