Show modal with origin selector before creating localization
statamic/cms pull request #6943
Opened 2022-10-24 13:20 UTC by arthurperton

As discussed, this PR shows a confirmation modal before creating a localization for an entry. The origin for the new localization will default to the first site, however in the modal you can choose a different origin if you like. 

<img width="1053" alt="Screenshot 2022-10-24 at 15 14 02" src="https://user-images.githubusercontent.com/4067531/197534990-adb31c3d-7e2b-48bb-bd83-914706d77826.png">

Feel free to update UI and text of course.

2022-10-24 17:04 UTC, arthurperton commented
I suspected you wouldn’t like that too much 😊 They’re not needed for the fix and they make the diff larger right. I’ll revert them 👍🏻

2022-10-24 18:06 UTC, jasonvarga commented
Thanks! Much easier to review the relevant parts.

2022-10-24 20:57 UTC, jasonvarga requested changes
If you only have 2 sites configured, you shouldn't get the modal at all since there's only one option to choose from.

2022-10-25 04:17 UTC, arthurperton commented
Ah yes, totally.

2022-10-26 16:54 UTC, jasonvarga commented on resources/js/components/entries/PublishForm.vue
> +            } else if (this.localizations.length > 2) {
The ability to cancel is a good enough reason to keep it. 👍

2022-10-26 18:17 UTC, merged

2022-11-01 16:54 UTC, tao commented
Is there a way to disable the modal from showing up? I already have an event to only translate the root entry from ages ago. https://github.com/statamic/cms/issues/4287

2022-11-01 17:05 UTC, tao commented
There needs to be a way to disable this before I can update, I can't have editors creating localisations from other languages besides English as the root.

2022-11-01 17:07 UTC, jasonvarga commented
The modal will only show options that they would have been able to use before.

2022-11-01 17:17 UTC, tao commented
There should be a way to support many different types of workflows with Multisite, the original issue was created back in Sep 2021 and we found a work-around, which I've been very happy with since then... now the pop-up is going to break the flow and confuse everyone if I update Statamic. 

Is there some Javascript we can add or custom Javascript I can run to disable this modal or auto-select English and suppress the pop-up?

2022-11-01 17:18 UTC, jasonvarga commented
I see what you mean. You were forcing the origin on the server side. So in your case, they could pick another site in the modal, even though it wouldn't use it because you override it.