Ability to use separate queue for Static Cache warm
statamic/cms pull request #7184
Opened 2022-12-09 12:34 UTC by robbanl

Having a big site with lots of entries, in my case 1000+, the cache warming using queue would fill the "default" queue making other more important jobs be really delayed. Adding this change would allow us to put the StaticWarm job on a separate queue and allows us to process the queue on a separate queue worker.

Adding the following into the `.env` file would make this magic happen:

```
STATAMIC_STATIC_WARM_QUEUE=cache_warm_queue
```

2022-12-09 14:50 UTC, jasonvarga requested changes
Please make this an option instead.

```
php please static:warm --queue=foo
```

And/or make a new config option in `config/statamic/stache.php`. Don't use the `env()` method directly.

2022-12-13 12:11 UTC, robbanl commented
Moved this into a setting in the stache configuration file, and falling back on default.

2022-12-13 15:10 UTC, jasonvarga requested changes

2022-12-13 15:10 UTC, jasonvarga commented on config/static_caching.php
> +    'warm_queue_name' => 'default',
```suggestion
    /*
    |--------------------------------------------------------------------------
    | Warm Queue
    |--------------------------------------------------------------------------
    |
    | Here you may define the name of the queue that requests will be pushed
    | onto when warming the static cache using the static:warm command.
    |
    */

    'warm_queue' => 'default',

```

2022-12-13 15:10 UTC, jasonvarga commented on src/Console/Commands/StaticWarm.php
> +            $this->line('Adding '.count($requests).' requests on queue "'.$staticWarmQueue.'"...');
```suggestion
            $queue = config('statamic.static_caching.warm_queue', 'default');
            $this->line('Adding '.count($requests).' requests on queue "'.$queue.'"...');
```

2022-12-14 16:25 UTC, jasonvarga commented
I might have a couple more edits actually. Would you be able to just give me permission so I can push to it?

2022-12-15 11:57 UTC, robbanl commented
> jasonvarga

Invite sent for repo https://github.com/codepeak/statamic-cms/ (write access)

2022-12-19 16:45 UTC, jasonvarga approved these changes

2022-12-19 16:55 UTC, merged