Allow setting ids inside sets
statamic/cms pull request #8407
Opened 2023-07-05 10:11 UTC by jonassiewertsen

2023-07-05 17:29 UTC, jasonvarga commented
I know you already asked about this PR before but I'm curious what the reason is for needing your own `id` field in there?

Is it because you used to have an id field in there before we added them?

2023-07-06 09:15 UTC, jonassiewertsen commented
One common example is Embedded stuff. Could be Twitter, Vimeo, Youtube etc or custom stuff. 

```yaml
embedded_something:
  id: 1234
  description: What a nice external content
```

As we are "only updating", we have that data being around from the past few years, which is being used by different external Systems as well.

2023-07-06 19:53 UTC, jasonvarga requested changes

2023-07-06 19:53 UTC, jasonvarga commented on src/Support/Traits/GetIdKey.php
There is a `src/Fieldtypes/RowId.php` class that is used to generate the Row ID value. I think that would be a more appropriate place to get the key/handle.

```php
class RowId
{
  public function handle()
  {
    return config('statamic.system.row_id_handle', 'id');
  }
}
```

Then you can do `RowId::handle()` within Replicator/Bard/Grid classes instead of `$this->getIdKey()`.

2023-07-06 19:54 UTC, jasonvarga commented on src/Http/Controllers/CP/Fields/FieldsController.php
If you want, you can leave this part to us. But I imagine it would involve passing a prop along within the blueprint/fieldset builders and up into the request.

2023-07-12 12:58 UTC, jonassiewertsen commented on src/Http/Controllers/CP/Fields/FieldsController.php
> The `id` should still be reserved at the top level.

It feels like talking about a short time solution and a long time solution. I am really unsure about the short time solution in this PR, as not breaking changes are possible, but maybe it's getting clearer if talking about the long time solution first?

Are we sharing the long time solution at all? Is there interested into changing that?

Let me explain:
- I think that field values should be separated and may not interfere at all with any kind of meta data. 
- I think that internal Statamic data may never conflict with user data
- Handles in fieldtypes should not be reserved

One example of a default result from Elasticsearch, which does make sure that values and meta information are separated:

![Bildschirmfoto 2023-07-12 um 13 46 09](https://github.com/statamic/cms/assets/38906163/a905b4be-da28-4798-a7a3-aedfe9dc0cb1)
(Green:  Values, Blue: Meta)

With that kind of structure, there cannot be conflicts.

**Statamic already does that in some parts of the application too:**

![Bildschirmfoto 2023-07-12 um 14 18 10](https://github.com/statamic/cms/assets/38906163/26341aa6-fd12-40ff-99da-a9116950199d)

Personally it feels like we are already close to make this behaviour. 
No more need for reserved key words in field handles ...

BUT there are parts where all of that structure is made completely flat again, like saving entries. 
![Bildschirmfoto 2023-07-12 um 14 22 41](https://github.com/statamic/cms/assets/38906163/e5e46d22-cb48-44f8-ab89-5456f7313576)
(the underscore Id comes from this PR. With the actual version 4, the user id would be overwritten)

My personal main question is, on how to make sure that meta data does not interfere in the "flat" version?

- Maybe with some kind of prefix? I am suggesting `_` or `__` as shown above
- With a nested approach
- Something third?

Using a prefix would be my personal choice to avoid nested data and keeping changes as minimal as possible.

Pros of this approach:
- No need for reserved keywords (only a prefix needs to be forbidden)
- It won't be a breaking change if more meta data is needed in the future
- No breaking change with existing data
- Statamics internal data can't interfere with user/application data

2023-07-12 12:59 UTC, jonassiewertsen commented on src/Support/Traits/GetIdKey.php
Yes, I totally agree!

2023-07-12 19:46 UTC, jasonvarga commented on src/Http/Controllers/CP/Fields/FieldsController.php
I agree that there are some overlaps and maybe some awkward decisions in the past. But this is a lot of work for what is IMO really an edge case: someone wanting to use a reserved word for a field.

There are plenty of places and reasons where we choose to not use underscores for "reserved" or "internal" things. Like `id` or `status` for example. If you want to reference an entry's ID in your template, you can (and should) use `{{ id }}`. It would be strange to need to do `{{ _id }}`.

2023-07-17 15:11 UTC, jonassiewertsen commented on src/Http/Controllers/CP/Fields/FieldsController.php
I made changes to follow your suggested approach, which looks nice and clean to me!

I had to use partialMocks for the RowId class in tests, which I hope is fine.

2023-07-17 15:11 UTC, jonassiewertsen commented on config/system.php
> +    'allow_ids_in_sets' => false,
Sound good to me. I changed it as suggested.

2023-07-17 15:29 UTC, jonassiewertsen commented on src/Http/Controllers/CP/Fields/FieldsController.php
> The `id` should still be reserved at the top level.
> 
> Maybe we can figure out a way to pass into this controller whether a top level field is being edited or not.
> 
> Something like:
> 
> ```
> $reserved[] = $isTopLevel ? 'id' : RowId::handle();
> ```

I am not quite sure if I understand this:

As I made the requested changes, it's now possible to rename the row id handle, so it's easy to rename to it to something different, in case your values interferes with legacy data. This solves our problem :-)

I made some manual tests with legacy data and it's working as expected too.

Which case did i miss, that we benefit from passing the information into the controller, wether we edit a top level field or not?

2023-08-10 18:56 UTC, jasonvarga commented on src/Http/Controllers/CP/Fields/FieldsController.php
Since this config now only controls what the id key will be inside Grid/Replicator/Bard it doesn't control what the id key will be at the top level. We want to continue to make `id` reserved at the top level.

2023-08-10 21:02 UTC, jonassiewertsen commented on src/Http/Controllers/CP/Fields/FieldsController.php
Sound good. Thanks!

2023-08-10 21:38 UTC, jasonvarga approved these changes

2023-08-10 21:45 UTC, merged