[4.x] Add 'Parent' column to entries fieldtype
statamic/cms pull request #8510
Opened 2023-07-29 08:33 UTC by duncanmcclean

This pull request adds a 'Parent' column to the Entries fieldtype when it's opened in a stack.

At the moment, if you have a collection's structured and looks like this:

* Home
* Locations
    * Location 1
        * Apartments
        * Amenities
        * Gallery
    * Location 2
        * Apartments
        * Amenities
        * Gallery

Then, when you open the entries fieldtype in a stack, it's hard to identify which 'Apartments' entry you're selecting. Sometimes you have to select in the stack, then open it up, check if it's the right one, then remove it and try again. It's painful and I'm surprised we haven't had a client complain yet 😅 

This PR fixes that issue by adding a 'Parent' column to the entries fieldtype results, when the collection has a structure.

<img width="1071" alt="image" src="https://github.com/statamic/cms/assets/19637309/28849b0e-487e-4639-920a-be7fe10e0846">

*^ screenshot from my sandbox site - the entries don't match the use case I just explained but I'm sure you can make sense of it*

Fixes #4187

2023-09-20 20:46 UTC, jackmcdade requested changes
Since there can be multiple collections, we'll need to have a smarter check than whatever's in the row, unfortunately.

2023-09-20 20:46 UTC, jackmcdade commented on resources/js/components/data-list/Table.vue
Since there can be multiple collections, we'll need to have a smarter check than whatever's in the row, unfortunately.

2023-09-20 20:47 UTC, jackmcdade commented on resources/js/components/data-list/Table.vue
Super redundant information lol – i never know the best place to put the thing so you get a "changes requested" state.

2023-10-02 19:14 UTC, jasonvarga commented
I think a more appropriate solution could be to have the selector display the tree view.

See: https://github.com/statamic/ideas/issues/666

(It would only be available if a single orderable collection is configured on the entries field)

2023-10-02 19:14 UTC, closed without merging