[4.x] Fix runtime behavior regression
statamic/cms pull request #8873
Opened 2023-10-21 00:57 UTC by JohnathonKoster

This PR fixes #8829.

An earlier PR #8818 introduced a behavior regression. While the behavior is *technically correct*, it doesn't play well with sites that were accidentally relying on the old behavior.

An example of where the old behavior before #8818 would apply incorrectly is when using the `asset` tag with the `url` parameter:

```antlers
{{ asset :url="image" }}
   {{# Do your thing. #}}
{{ /asset }}
```

Because `url` also matches a modifier name, the previous over-aggressive check would catch this tag and isolate its parsing/rendering. This PR re-introduces this old behavior when a tag returns an associative array, while preserving the corrected behavior #8818 was trying to achieve.

This behavior regression is incredibly difficult to track down and correct within sites using a page builder-type setup, where its not obvious what's being included when/by-what. I've verified it on a site (related to the attached issue), but it is highly likely to impact more.

New tests have also been added to catch this behavior, but there is the possibility that it doesn't account for *all* of the weird previous behavior of having the over-aggressive check apply to everything.

2024-03-06 23:06 UTC, jasonvarga requested changes
> Regardless of which action is taken reverting 8818 or accepting this PR, there will be strange behavior in some scenarios until it can be resolved in a breaking-change version.

What would a breaking-change solution look like? Since we're working on v5, let's just do whatever that is.

2024-03-08 01:22 UTC, JohnathonKoster commented
> > Regardless of which action is taken reverting 8818 or accepting this PR, there will be strange behavior in some scenarios until it can be resolved in a breaking-change version.
> 
> What would a breaking-change solution look like? Since we're working on v5, let's just do whatever that is.

The changes in https://github.com/statamic/cms/pull/8818 were accidentally the breaking changes (even if they fixed an inconsistency/bug). Tag pairs that happened to have the same names as modifiers would subtly change the behavior of things at the time. The breaking change would have been to keep 8818, which is the current state of 4.x without this PR

2024-03-08 15:09 UTC, jasonvarga commented
What's "more correct" though? The way it is now?

If we introduced a breaking change in a non-major release, that's obviously a no-no for semver. But maybe we just call a whoopsie, ask the semver gods for forgiveness, and leave it alone. It's been this way for almost 5 months. People running into it have probably adapted to it. If we were to revert it now it could probably be considered another breaking change.

2024-03-08 15:20 UTC, JohnathonKoster commented
>What's "more correct" though? The way it is now?

In my opinion, the way it is now is the correct behavior 👍

2024-03-08 15:34 UTC, jasonvarga commented
Okay, let's just leave it then.

2024-03-08 15:34 UTC, closed without merging