[4.x] Antlers: Adds support for disabling Antlers entirely inside tag parameter content
statamic/cms pull request #8887
Opened 2023-10-28 16:53 UTC by JohnathonKoster

This PR adds support for disabling the parsing of Antlers entirely when supplying parameter values by introducing new syntax.

For example, let us consider the following form tag using the existing syntax to escape `{` and `}` safely inside parameter content:

```antlers
{{ form:contact x-data="@{ open: false, toggle() @{ this.open = ! this.open @} @}" }}
    ...
{{ /form:contact }}
```

With the changes in this PR, we could now just prefix our parameter name with a single backslash (`\`) character:

```antlers
{{ form:contact \x-data="{ open: false, toggle() { this.open = ! this.open } }" }}
    ...
{{ /form:contact }}
```

Notes/considerations:

* There is no way to get back into Antlers inside the parameter when using the `\` syntax. This syntax completely disables the recursive parser
* Breaking change concerns: none. The `\parameter="something"` is currently illegal syntax, and won't produce parameters at all
* Why not use `@parameter="something"` to indicate the escaped content? While this would be nice for consistency, it would be a breaking change since using parameters like `@click="doTheRoar()"` is already supported

2023-10-29 09:12 UTC, ryanmitchell commented
Just thinking out loud, but if you needed the output of backend variables in the JS, would something like this work?

```antlers
{{? $js = '{ open: '.$variable.', toggle() { this.open = ! this.open } }' ?}}
{{ form:contact :\x-data="js" }}
    ...
{{ /form:contact }}
```

2023-10-29 12:18 UTC, JohnathonKoster commented
> Just thinking out loud, but if you needed the output of backend variables in the JS, would something like this work?
> 
> ```
> {{? $js = '{ open: '.$variable.', toggle() { this.open = ! this.open } }' ?}}
> {{ form:contact :\x-data="js" }}
>     ...
> {{ /form:contact }}
> ```

For that, you could accomplish that without this PR and just do `:x-data="js"`

2023-10-30 20:02 UTC, jasonvarga commented
> Breaking change concerns: none. The `\parameter="something"` is currently illegal syntax, and won't produce parameters at all
> Why not use `@parameter="something"` to indicate the escaped content? While this would be nice for consistency, it would be a breaking change since using parameters like `@click="doTheRoar()"` is already supported

Adding another symbol is a bit confusing IMO. "Use a `@` to escape these, but a `\` to escape these..."

I would personally prefer `@` to be used as the character to be consistent.

That would make it a breaking change, so we could just have this target 5.x.

Along with making attributes on form-rendering tags (like `form:create`, `user:password_form`, etc) require an `attr:` prefix, like we do on the `vite` tag. The `attr:` prefix already works on form tags, but _also_ non-prefixed params. In v5 we can enforce the prefix.

So, as part of the upgrade guide, you'd need to do this on your form tags:

```diff
{{ form:create
     in="contact"
     redirect="/thanks"
-    class="foo"
-    @submit="submitForm"
+    attr:class="foo"
+    attr:@submit="submitForm"
}}
```

As for this:

> I could likely get something similar to the following working without a ton of additional effort, but would need to gauge utility/interest (potentially feedback from Core on whether to continue with it)

Let's just stick with escaping the whole parameter content for now. This sounds super complicated. 😄

2023-10-30 20:04 UTC, jackmcdade commented
I concur with @jasonvarga.

2023-10-30 20:08 UTC, jasonvarga requested changes
Please target `master`, and just change the prefix to `@`.

We can tackle the form `attr:` prefix changes in a separate PR.

2023-10-30 20:20 UTC, JohnathonKoster commented
Will do; thanks for the awesome review 🙂

2023-10-31 02:03 UTC, jasonvarga commented
I just updated `master` to be in sync with 4.x. Can you merge `master` into your branch? Then there won't be 200+ changed files. 😆

2023-10-31 13:39 UTC, JohnathonKoster commented
> I just updated `master` to be in sync with 4.x. Can you merge `master` into your branch? Then there won't be 200+ changed files. 😆

Done!

2024-02-29 00:07 UTC, JohnathonKoster commented
> Hey John, this is great.
> 
> But after merging `master` back into this, there's a failing test. I'm not sure where it was introduced. I don't think it's this PR though, but maybe you can figure it out?
> 
> There's also one deprecation warning - don't worry about that for now.

Looks like the space was trimmed out from the template string during the merge. Digging through different branches, I can't find any that had removed this space (and is present on `master`)🤔

<img width="902" alt="image" src="https://github.com/statamic/cms/assets/5232890/896da0ad-1e9a-48a3-9ed0-00aa33272977">

2024-02-29 14:23 UTC, jasonvarga commented
You're right, it was in that merge. My fault. Must have been my editor automatically stripping trailing spaces when I saved for that merge conflict, and I didn't notice. Thanks.

2024-02-29 15:15 UTC, jasonvarga approved these changes

2024-02-29 15:16 UTC, merged