[4.x] Fix super not saving on eloquent users
statamic/cms pull request #8979
Opened 2023-11-13 11:04 UTC by ryanmitchell

As [reported here](https://github.com/statamic/cms/issues/8978), adding super to an existing eloquent user would not save/persist.

This PR fixes that by setting it explicitly on saveToDatabase() and adds test coverage to ensure it works going forward.

2023-11-13 17:21 UTC, jasonvarga requested changes
Rather than changing this, I think we could add another case inside `__set` instead that sets `super` on the model, like we do with `timestamps`.

2023-11-13 17:39 UTC, ryanmitchell commented
Yeah I had that originally, ended up this way because when you set it to be false (line 160 of the test I added) it didnt unset super.

2023-11-14 08:28 UTC, ryanmitchell commented
My mistake, figured out the issue was due to me allowing the property to be set on $user, so __set was only called the first time.

2023-11-14 19:14 UTC, jasonvarga approved these changes

2023-11-14 19:22 UTC, merged