[4.x] Generate slugs with Laravel's `Str::slug()` helper
statamic/cms pull request #9440
Opened 2024-02-01 12:17 UTC by duncanmcclean

This pull request changes the way slugs are generated in the Control Panel. 

Until now, we've now used a library called `speakingurl`. It worked fine for generating slugs based on English strings but it didn't work so well for other languages, like [German](https://github.com/statamic/cms/issues/6985) & [Chinese](https://github.com/statamic/cms/issues/2817).

Rather than implementing another JS library, we've decided to generate the slugs using Laravel's [`Str::slug()`](https://laravel.com/docs/master/strings#method-str-slug) helper which works better with other languages. 

We had made some modifications to our `$slugify` helper to workaround issues like smart quotes, hiphens separated by spaces, etc. I've added tests for these cases and Laravel's string helper seems to handle them as expected.

Due to slug generation now being done on the server-side & needing to perform network requests, I've had to make changes to how we use the `$slugify` helper in various places across the codebase.

Closes #2817.

2024-02-01 14:38 UTC, jasonvarga requested changes

2024-02-01 14:38 UTC, jasonvarga commented on resources/js/components/blueprints/Sections.vue
> +            console.log(handle);
🪵

2024-02-01 14:38 UTC, jasonvarga commented on resources/js/components/blueprints/Sections.vue
> +
🪵

2024-02-01 14:38 UTC, jasonvarga commented on resources/js/plugins/slugify.js
> +            return new Promise((resolve, reject) => {
Since the behavior of `$slugify` is changing to a promise, this PR should probably be targeting `master`.

2024-02-01 14:38 UTC, jasonvarga commented on tests/Feature/Fieldtypes/SlugTest.php
> +            'german_characters' => ['Björn Müller', '-', 'de', 'bjoern-mueller'],
Can we throw an Arabic example in here? That's what really prompted this so we should make sure it's covered.

2024-02-01 16:53 UTC, jasonvarga commented on tests/Feature/Fieldtypes/SlugTest.php
> +            'german_characters' => ['Björn Müller', '-', 'de', 'bjoern-mueller'],
I just grabbed a phrase from Google Translate. Good Morning in Arabic is `صباح الخير` 
If you pass it into `Str::slug` it outputs `sbah-alkhyr`. Plop that into the test using `ar`.👍 
We know it works, we just want to make sure it's in the test.

2024-02-01 16:56 UTC, duncanmcclean commented on tests/Feature/Fieldtypes/SlugTest.php
> +            'german_characters' => ['Björn Müller', '-', 'de', 'bjoern-mueller'],
Added!

The only reason I asked for one was the fact ChatGPT was giving me titles & slugs that didn't match up correctly so wanted a more realistic example.

2024-03-20 21:19 UTC, jasonvarga approved these changes

2024-03-20 21:34 UTC, merged