[5.x] Scaffold PHPUnit test suite with `make:addon` command
statamic/cms pull request #9593
Opened 2024-02-27 09:06 UTC by duncanmcclean

This pull request improves the `make:addon` command by automatically scaffolding a PHPUnit test suite when new addons are created.

2024-02-29 17:17 UTC, jasonvarga requested changes
The composer install step failed for me. Not sure how it passed for you. It was complaining about a plugin not being allowed.

Adding this to the composer.json.stub fixes it:

```json
    "config": {
        "allow-plugins": {
            "pixelfear/composer-dist-plugin": true
        }
    }
```

Also, the tests don't want to run for me. Did they work for you?

```
sandbox/addons/pixelfear/charlie on  master [!?] 
→ ./vendor/bin/phpunit

Fatal error: Uncaught Error: Class "Statamic\Extend\AddonTestCase" not found in /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/tests/TestCase.php:8
Stack trace:
#0 /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/vendor/composer/ClassLoader.php(576): include()
#1 /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/jason/Co...')
#2 /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/tests/ExampleTest.php(5): Composer\Autoload\ClassLoader->loadClass('Pixelfear\\Charl...')
#3 /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/Users/jason/Co...')
```

Funnily, using VSCode's "Better PHPUnit" extension to run the test from the file itself _does_ work:

```
Executing task: valet php ./vendor/bin/phpunit /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/tests/ExampleTest.php --configuration /Users/jason/Code/statamic/sandbox/addons/pixelfear/charlie/phpunit.xml 

PHPUnit 9.6.17 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.180, Memory: 34.00 MB

OK (1 test, 0 assertions)
```

2024-03-01 12:40 UTC, duncanmcclean commented
> The composer install step failed for me. Not sure how it passed for you. It was complaining about a plugin not being allowed.

Weird, it was definitely working for me. 🤔 

Anyways, I've added that plugin to the `composer.json` stub. Maybe try again and see if it works this time?

> Also, the tests don't want to run for me. Did they work for you?

It'll be because the `AddonTestCase` is only available on `master` but when it installs `statamic/cms` in the addon, it's installing the latest v4 tag which doesn't include that class.

You probably need to symlink your local `cms` repository before running the tests. Once v5 is tagged, this shouldn't be an issue.

2024-03-01 18:29 UTC, jasonvarga commented
You're right!

I changed the stub to `"statamic/cms": "dev-include-tests-in-make-addon-stubs as 4.50.0"`, ran `make:addon`, and I was able to run the tests immediately. That way it could work without needing to symlink my cms first.

Since it works, I've bumped the constraint to `^5.0` since that's what it's gonna be when this is shipped.

2024-03-01 18:29 UTC, jasonvarga approved these changes

2024-03-01 18:33 UTC, merged