[5.x] Move sites out of config
statamic/cms pull request #9632
Opened 2024-03-02 04:49 UTC by jesseleite

wip

2024-04-02 17:06 UTC, jasonvarga requested changes

2024-04-02 23:02 UTC, jesseleite commented on src/Providers/AppServiceProvider.php
> +        $this->app->singleton(Sites::class, fn () => new Sites);
Facades are singletons, so I think I can actually just remove that line altogether.

2024-04-08 15:53 UTC, jasonvarga approved these changes

2024-04-09 17:37 UTC, merged

2024-04-10 12:54 UTC, robdekort commented
I'm wondering if this should be in the CP nav under `Content` by default. Perhaps it's better under `Tools` or `Utilities`. It's something you rarely need.

2024-04-10 18:19 UTC, jasonvarga commented
That's a good thought.

2024-05-30 13:14 UTC, ajnsn commented
With more complex page configurations, it is now much more difficult to achieve a reliable result with all these curly brackets as placeholders for URLs etc. - especially if you have also used PHP enums or collections/arrays in the "attributes".

Code analysis and testing also now seem more difficult to achieve.

Is there still a way e.g. to override this `sites.yaml` using PHP or is something like that planned? 

Thanks!

2024-05-30 13:27 UTC, duncanmcclean commented
We're not planning on adding back a PHP method for configuring sites.

However, in your case, you could potentially override the sites in a service provider, like this:

```php
// app/Providers/AppServiceProvider.php

use Statamic\Facades\Site;
use Statamic\Statamic;

Statamic::booted(function () {
    Site::setSites([
        'default' => [
            'name' => 'Default',
            'locale' => 'en_US',
            'url' => YourEnum::Url,
        ],
    ]);
});
```

2024-05-30 13:37 UTC, ajnsn commented
Thanks!