[5.x] Remove unnecessary controller `destroy` methods
statamic/cms pull request #9689
Opened 2024-03-08 17:25 UTC by duncanmcclean

This pull request removes a few instances of `destroy` methods in CP Controllers that have since been replaced with actions.

I scanned through some of the other actions we have and couldn't find any others with old routes/controllers. It *looks* like it's just the delete ones that weren't deleted.

Addresses #9681.

2024-03-12 21:58 UTC, jasonvarga requested changes

2024-03-12 21:58 UTC, jasonvarga commented on src/Http/Controllers/CP/Assets/AssetsController.php
Didn't add `->except('destroy')` to the route resource for a reason?

2024-03-13 14:18 UTC, duncanmcclean commented on src/Http/Controllers/CP/Assets/AssetsController.php
Whoops, no reason. Added it now!

2024-03-13 14:32 UTC, jasonvarga approved these changes

2024-03-13 15:00 UTC, merged