[5.x] Laravel Prompts
statamic/cms pull request #9720
Opened 2024-03-12 20:57 UTC by duncanmcclean

This pull request introduces [Laravel Prompts](https://laravel.com/docs/11.x/prompts) to enhance some our existing commands. We couldn't do this until now due to us needing to support PHP 8.1.

In this PR, we've only "enhanced" the commands where we have confirm dialogs, progress bars or could use a spinner (like the `install:ssg` command).

2024-04-12 13:50 UTC, jasonvarga requested changes

2024-04-12 15:44 UTC, duncanmcclean commented on src/Console/Commands/AddonsDiscover.php
Done!

2024-04-12 20:45 UTC, jasonvarga submitted a review, later dismissed

2024-04-15 09:34 UTC, duncanmcclean commented
> Some test are failing due to my last changes. My bad. I'll fix them on Monday unless you beat me to it.

Done 😆 

When we're using components, assertions need to do `->expectsOutputToContain()` instead of `->expectsOutput()`. Presumably, this is because the components stuff adds other stuff to the output.

2024-04-15 13:54 UTC, merged